plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
include ':app'
rootProject.name='science'
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        // jcenter()
    }
}