#!/usr/bin/env python3
"""
Translate all untranslated strings using manual translation dictionaries.
This provides accurate translations for scientific and technical terminology.
"""
import os
import sys
import xml.etree.ElementTree as ET

# German translations
GERMAN_TRANSLATIONS = {
    "kelvin": "Kelvin",
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit",
    "element_description_title": "Beschreibung",
    "favorite_settings_general": "Allgemein",
    "favorite_settings_nuclear": "Nuklear",
    "sources_settings_title": "Quellen",
    "sources_wwe_text": "Mackenzie L. Davis, (2019). Water and wastewater Engineering: Design Principles and Practise, second edition. ISBN: 978-1-260-13227-4",
    "isotopes_title": "Isotope",
    "clear_cache_text": "cache_size",
    "submit_bug": "Fehler",
    "info_title": "Information",
    "git_title": "Github",
    "activity_ph_neutral": "Neutral",
    "wikipedia_license": "Wikipedia Commons",
    "sothree_license": "Android Sliding Up Panel",
    "calculator_formula": "Formel",
    "short_voltage": "Spannung",
    "bug": "Fehler",
    "no_results": "Keine Ergebnisse",
    "additional_data_item": "- Zusätzliche Daten:",
    "additional_flashcards_games": "Zusätzliche Karteikarten-Spiele:",
    "additional_properties_requires_pro": "Zusätzliche Eigenschaften erfordern PRO-Version. Holen Sie sich PRO, um mehr Daten und Tabellen freizuschalten:",
    "additional_tables_item": "- Zusätzliche Tabellen:",
    "all_core_features": "Alle Kernfunktionen",
    "and_more_item": "- Und mehr",
    "appearance_colon": "Aussehen:",
    "atomic_mass_colon": "Atommasse:",
    "atomic_number_label": "Ordnungszahl:",
    "atomic_radius_calculated_colon": "Atomradius (berechnet):",
    "atomic_radius_empirical_colon": "Atomradius (empirisch):",
    "atomic_weight_relative_atomic_mass": "Atomgewicht (relative Atommasse):",
    "balance_equation": "Gleichung ausgleichen:",
    "balance_equation_colon": "Gleichung ausgleichen:",
    "block_colon": "Block:",
    "boiling_point_colon": "Siedepunkt:",
    "brinell_hardness_colon": "Brinellhärte:",
    "calculations": "Berechnungen",
    "calculations_stat": "Berechnungen",
    "card_order": "Kartenreihenfolge",
    "color_label": "Farbe: ",
    "constants_table_label": "Konstantentabelle:",
    "correct": "Richtig",
    "correct_answer": "Richtige Antwort: %s",
    "cristal_structure_label": "Kristallstruktur: ",
    "currently_no_favorites": "Derzeit keine Favoriten",
    "density_colon": "Dichte:",
    "density_label": "Dichte: ",
    "electron_shell_colon": "Elektronenschale:",
    "electronegativity_colon": "Elektronegativität:",
    "elements_included_will_be_shown_here": "Enthaltene Elemente werden hier angezeigt",
    "elements_opened": "Geöffnete Elemente",
    "emission_spectrum_colon": "Emissionsspektrum:",
    "enable_zoom_in_tables": "Zoom in Tabellen aktivieren",
    "experimental": "Experimentell",
    "favorites_colon": "Favoriten:",
    "fifty_lives_in_flashcards": "50 Leben in Karteikarten:",
    "finished_game_xp": "Spiel beendet: +%dxp",
    "formula_will_be_displayed_here": "Formel wird hier angezeigt",
    "fusion_heat_colon": "Schmelzwärme:",
    "game_results": "Spielergebnisse",
    "get_pro_button": "PRO holen",
    "get_pro_plus_button": "PRO+ holen",
    "go_online_for_emission_lines": "Online gehen für Emissionslinien",
    "go_pro_more_features": "Gehe Pro - mehr Funktionen",
    "go_pro_school_start_sale": "GEHE PRO - SCHULSTART-VERKAUF",
    "group_label": "Gruppe: ",
    "hardness_label": "Härte: ",
    "isotopes_table_description": "Eine Tabelle mit Isotopen für verschiedene Elemente sowie Halbwertszeit-, Massen-, Protonen-, Neutronen- und Nukleonendaten.",
    "level_x_y": "Level X-Y",
    "lives_label": "Leben: %s",
    "lives_lost_detail": "Verlorene Leben: %1$d (%2$d pro falscher/Zeitüberschreitungs-Antwort)",
    "lives_unlimited": "Leben: ∞",
    "magnetism_label": "Magnetismus: ",
    "melting_point_colon": "Schmelzpunkt:",
    "most_advanced": "Am fortschrittlichsten",
    "new_label": "NEU",
    "next_life_in": "Nächstes Leben in %1$d Minuten und %2$d Sekunden.\nSie erhalten %3$d Leben%4$s.",
    "no_image": "Kein Bild",
    "non_pro": "NICHT-PRO",
    "option_placeholder": "Option %d",
    "out_of_lives_hours": "Keine Leben mehr! Mehr Leben in %1$d Stunden, %2$d Minuten und %3$d Sekunden.",
    "out_of_lives_minutes": "Keine Leben mehr! Mehr Leben in %1$d Minuten und %2$d Sekunden.",
    "perfect_all_correct_xp": "Perfekt (Alles richtig): +%dxp",
    "phase_stp_colon": "Phase (STP):",
    "pro_plus_rewards": "PRO+ Belohnungen: %s",
    "pro_plus_user": "PRO+ BENUTZER",
    "pro_plus_version": "PRO+ Version",
    "pro_user": "PRO BENUTZER",
    "pro_version": "PRO Version",
    "progress_xp": "%1$d/%2$d",
    "question_text": "Fragetext",
    "questions_correct_xp": "Richtige Fragen: +%dxp",
    "rate": "Bewerten",
    "rate_app": "App bewerten",
    "rate_app_description": "Teilen Sie uns mit, was Sie von der App halten, indem Sie sie im Play Store bewerten!",
    "reaction_balancer": "Reaktionsausgleicher:",
    "score_summary": "Punktzahl: %1$d/%2$d",
    "searches": "Suchen",
    "solubility_table": "Löslichkeitstabelle",
    "specific_heat_capacity_colon": "Spezifische Wärmekapazität:",
    "streak_label": "Streifen: ",
    "time_up": "Zeit ist abgelaufen",
    "tools": "Werkzeuge",
    "total_xp_stat": "Gesamt-XP: %d",
    "type_label": "Typ: ",
    "unit_conversion_format": "%1$s %2$s → %3$s %4$s (%5$s)",
    "unlock_advanced_data_and_additional_flashcards": "Schalten Sie erweiterte Daten und zusätzliche Karteikarten frei.",
    "unlock_advanced_data_and_extra_atomic_content": "Schalten Sie erweiterte Daten und zusätzliche atomare Inhalte frei.",
    "usage_statistics": "Nutzungsstatistiken",
    "vaporization_heat_colon": "Verdampfungswärme:",
    "wrong": "Falsch",
    "xp_bonus": "+%d%% Bonus-XP",
    "you_have_full_lives": "Sie haben volle Leben!",
    "your_answer": "Ihre Antwort: %s",
    "achievement_reached_prefix": "Erfolg erreicht: ",
}

# French translations
FRENCH_TRANSLATIONS = {
    "kelvin": "Kelvin",
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit",
    "element_description_title": "Description",
    "favorite_settings_general": "Général",
    "favorite_settings_nuclear": "Nucléaire",
    "sources_settings_title": "Sources",
    "sources_wwe_text": "Mackenzie L. Davis, (2019). Water and wastewater Engineering: Design Principles and Practise, second edition. ISBN: 978-1-260-13227-4",
    "isotopes_title": "Isotopes",
    "clear_cache_text": "cache_size",
    "submit_bug": "Bug",
    "info_title": "Information",
    "git_title": "Github",
    "activity_ph_neutral": "Neutre",
    "wikipedia_license": "Wikipedia Commons",
    "sothree_license": "Android Sliding Up Panel",
    "calculator_formula": "Formule",
    "short_voltage": "Tension",
    "bug": "Bug",
    "no_results": "Aucun résultat",
    "additional_data_item": "- Données supplémentaires:",
    "additional_flashcards_games": "Jeux de cartes mémoire supplémentaires:",
    "additional_properties_requires_pro": "Les propriétés supplémentaires nécessitent la version PRO. Obtenez PRO pour débloquer plus de données et de tableaux:",
    "additional_tables_item": "- Tableaux supplémentaires:",
    "all_core_features": "Toutes les fonctionnalités principales",
    "and_more_item": "- Et plus encore",
    "appearance_colon": "Apparence:",
    "atomic_mass_colon": "Masse atomique:",
    "atomic_number_label": "Numéro atomique:",
    "atomic_radius_calculated_colon": "Rayon atomique (calculé):",
    "atomic_radius_empirical_colon": "Rayon atomique (empirique):",
    "atomic_weight_relative_atomic_mass": "Poids atomique (masse atomique relative):",
    "balance_equation": "Équilibrer l'équation:",
    "balance_equation_colon": "Équilibrer l'équation:",
    "block_colon": "Bloc:",
    "boiling_point_colon": "Point d'ébullition:",
    "brinell_hardness_colon": "Dureté Brinell:",
    "calculations": "Calculs",
    "calculations_stat": "Calculs",
    "card_order": "Ordre des cartes",
    "color_label": "Couleur: ",
    "constants_table_label": "Table des constantes:",
    "correct": "Correct",
    "correct_answer": "Réponse correcte: %s",
    "cristal_structure_label": "Structure cristalline: ",
    "currently_no_favorites": "Actuellement aucun favori",
    "density_colon": "Densité:",
    "density_label": "Densité: ",
    "electron_shell_colon": "Couche électronique:",
    "electronegativity_colon": "Électronégativité:",
    "elements_included_will_be_shown_here": "Les éléments inclus seront affichés ici",
    "elements_opened": "Éléments ouverts",
    "emission_spectrum_colon": "Spectre d'émission:",
    "enable_zoom_in_tables": "Activer le zoom dans les tableaux",
    "experimental": "Expérimental",
    "favorites_colon": "Favoris:",
    "fifty_lives_in_flashcards": "50 vies dans les cartes mémoire:",
    "finished_game_xp": "Jeu terminé: +%dxp",
    "formula_will_be_displayed_here": "La formule sera affichée ici",
    "fusion_heat_colon": "Chaleur de fusion:",
    "game_results": "Résultats du jeu",
    "get_pro_button": "Obtenir PRO",
    "get_pro_plus_button": "Obtenir PRO+",
    "go_online_for_emission_lines": "Aller en ligne pour les lignes d'émission",
    "go_pro_more_features": "Passer Pro - plus de fonctionnalités",
    "go_pro_school_start_sale": "PASSER PRO - VENTE DE RENTRÉE SCOLAIRE",
    "group_label": "Groupe: ",
    "hardness_label": "Dureté: ",
    "isotopes_table_description": "Un tableau avec les isotopes pour différents éléments ainsi que les données de demi-vie, masse, proton, neutron et nucléons.",
    "level_x_y": "Niveau X-Y",
    "lives_label": "Vies: %s",
    "lives_lost_detail": "Vies perdues: %1$d (%2$d par réponse incorrecte/timeout)",
    "lives_unlimited": "Vies: ∞",
    "magnetism_label": "Magnétisme: ",
    "melting_point_colon": "Point de fusion:",
    "most_advanced": "Le plus avancé",
    "new_label": "NOUVEAU",
    "next_life_in": "Prochaine vie dans %1$d minutes et %2$d secondes.\nVous gagnerez %3$d vie%4$s.",
    "no_image": "Pas d'image",
    "non_pro": "NON-PRO",
    "option_placeholder": "Option %d",
    "out_of_lives_hours": "Plus de vies! Plus de vies dans %1$d heures, %2$d minutes et %3$d secondes.",
    "out_of_lives_minutes": "Plus de vies! Plus de vies dans %1$d minutes et %2$d secondes.",
    "perfect_all_correct_xp": "Parfait (Tout correct): +%dxp",
    "phase_stp_colon": "Phase (STP):",
    "pro_plus_rewards": "Récompenses PRO+: %s",
    "pro_plus_user": "UTILISATEUR PRO+",
    "pro_plus_version": "Version PRO+",
    "pro_user": "UTILISATEUR PRO",
    "pro_version": "Version PRO",
    "progress_xp": "%1$d/%2$d",
    "question_text": "Texte de la question",
    "questions_correct_xp": "Questions correctes: +%dxp",
    "rate": "Évaluer",
    "rate_app": "Évaluer l'application",
    "rate_app_description": "Faites-nous savoir ce que vous pensez de l'application en l'évaluant sur le Play Store!",
    "reaction_balancer": "Équilibreur de réaction:",
    "score_summary": "Score: %1$d/%2$d",
    "searches": "Recherches",
    "solubility_table": "Table de solubilité",
    "specific_heat_capacity_colon": "Capacité thermique spécifique:",
    "streak_label": "Série: ",
    "time_up": "Temps écoulé",
    "tools": "Outils",
    "total_xp_stat": "XP total: %d",
    "type_label": "Type: ",
    "unit_conversion_format": "%1$s %2$s → %3$s %4$s (%5$s)",
    "unlock_advanced_data_and_additional_flashcards": "Débloquez des données avancées et des cartes mémoire supplémentaires.",
    "unlock_advanced_data_and_extra_atomic_content": "Débloquez des données avancées et du contenu atomique supplémentaire.",
    "usage_statistics": "Statistiques d'utilisation",
    "vaporization_heat_colon": "Chaleur de vaporisation:",
    "wrong": "Incorrect",
    "xp_bonus": "+%d%% bonus xp",
    "you_have_full_lives": "Vous avez toutes vos vies!",
    "your_answer": "Votre réponse: %s",
    "achievement_reached_prefix": "Succès atteint: ",
}

# Spanish translations (applicable to all Spanish variants)
SPANISH_TRANSLATIONS = {
    "kelvin": "Kelvin",
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit",
    "element_description_title": "Descripción",
    "favorite_settings_general": "General",
    "favorite_settings_nuclear": "Nuclear",
    "sources_settings_title": "Fuentes",
    "sources_wwe_text": "Mackenzie L. Davis, (2019). Water and wastewater Engineering: Design Principles and Practise, second edition. ISBN: 978-1-260-13227-4",
    "isotopes_title": "Isótopos",
    "clear_cache_text": "cache_size",
    "submit_bug": "Error",
    "info_title": "Información",
    "git_title": "Github",
    "activity_ph_neutral": "Neutro",
    "wikipedia_license": "Wikipedia Commons",
    "sothree_license": "Android Sliding Up Panel",
    "calculator_formula": "Fórmula",
    "short_voltage": "Voltaje",
    "bug": "Error",
    "no_results": "Sin resultados",
    "additional_data_item": "- Datos adicionales:",
    "additional_flashcards_games": "Juegos de tarjetas adicionales:",
    "additional_properties_requires_pro": "Las propiedades adicionales requieren la versión PRO. Obtenga PRO para desbloquear más datos y tablas:",
    "additional_tables_item": "- Tablas adicionales:",
    "all_core_features": "Todas las funciones principales",
    "and_more_item": "- Y más",
    "appearance_colon": "Apariencia:",
    "atomic_mass_colon": "Masa atómica:",
    "atomic_number_label": "Número atómico:",
    "atomic_radius_calculated_colon": "Radio atómico (calculado):",
    "atomic_radius_empirical_colon": "Radio atómico (empírico):",
    "atomic_weight_relative_atomic_mass": "Peso atómico (masa atómica relativa):",
    "balance_equation": "Balancear ecuación:",
    "balance_equation_colon": "Balancear ecuación:",
    "block_colon": "Bloque:",
    "boiling_point_colon": "Punto de ebullición:",
    "brinell_hardness_colon": "Dureza Brinell:",
    "calculations": "Cálculos",
    "calculations_stat": "Cálculos",
    "card_order": "Orden de tarjetas",
    "color_label": "Color: ",
    "constants_table_label": "Tabla de constantes:",
    "correct": "Correcto",
    "correct_answer": "Respuesta correcta: %s",
    "cristal_structure_label": "Estructura cristalina: ",
    "currently_no_favorites": "Actualmente sin favoritos",
    "density_colon": "Densidad:",
    "density_label": "Densidad: ",
    "electron_shell_colon": "Capa electrónica:",
    "electronegativity_colon": "Electronegatividad:",
    "elements_included_will_be_shown_here": "Los elementos incluidos se mostrarán aquí",
    "elements_opened": "Elementos abiertos",
    "emission_spectrum_colon": "Espectro de emisión:",
    "enable_zoom_in_tables": "Habilitar zoom en tablas",
    "experimental": "Experimental",
    "favorites_colon": "Favoritos:",
    "fifty_lives_in_flashcards": "50 vidas en tarjetas:",
    "finished_game_xp": "Juego terminado: +%dxp",
    "formula_will_be_displayed_here": "La fórmula se mostrará aquí",
    "fusion_heat_colon": "Calor de fusión:",
    "game_results": "Resultados del juego",
    "get_pro_button": "Obtener PRO",
    "get_pro_plus_button": "Obtener PRO+",
    "go_online_for_emission_lines": "Ir en línea para líneas de emisión",
    "go_pro_more_features": "Ir Pro - más funciones",
    "go_pro_school_start_sale": "IR PRO - VENTA DE INICIO ESCOLAR",
    "group_label": "Grupo: ",
    "hardness_label": "Dureza: ",
    "isotopes_table_description": "Una tabla con isótopos para diferentes elementos, así como datos de vida media, masa, protones, neutrones y nucleones.",
    "level_x_y": "Nivel X-Y",
    "lives_label": "Vidas: %s",
    "lives_lost_detail": "Vidas perdidas: %1$d (%2$d por respuesta incorrecta/tiempo agotado)",
    "lives_unlimited": "Vidas: ∞",
    "magnetism_label": "Magnetismo: ",
    "melting_point_colon": "Punto de fusión:",
    "most_advanced": "Más avanzado",
    "new_label": "NUEVO",
    "next_life_in": "Próxima vida en %1$d minutos y %2$d segundos.\nGanarás %3$d vida%4$s.",
    "no_image": "Sin imagen",
    "non_pro": "NO-PRO",
    "option_placeholder": "Opción %d",
    "out_of_lives_hours": "¡Sin vidas! Más vidas en %1$d horas, %2$d minutos y %3$d segundos.",
    "out_of_lives_minutes": "¡Sin vidas! Más vidas en %1$d minutos y %2$d segundos.",
    "perfect_all_correct_xp": "Perfecto (Todo correcto): +%dxp",
    "phase_stp_colon": "Fase (STP):",
    "pro_plus_rewards": "Recompensas PRO+: %s",
    "pro_plus_user": "USUARIO PRO+",
    "pro_plus_version": "Versión PRO+",
    "pro_user": "USUARIO PRO",
    "pro_version": "Versión PRO",
    "progress_xp": "%1$d/%2$d",
    "question_text": "Texto de pregunta",
    "questions_correct_xp": "Preguntas correctas: +%dxp",
    "rate": "Calificar",
    "rate_app": "Calificar aplicación",
    "rate_app_description": "¡Déjanos saber qué piensas de la aplicación calificándola en Play Store!",
    "reaction_balancer": "Balanceador de reacciones:",
    "score_summary": "Puntuación: %1$d/%2$d",
    "searches": "Búsquedas",
    "solubility_table": "Tabla de solubilidad",
    "specific_heat_capacity_colon": "Capacidad calorífica específica:",
    "streak_label": "Racha: ",
    "time_up": "Tiempo agotado",
    "tools": "Herramientas",
    "total_xp_stat": "XP total: %d",
    "type_label": "Tipo: ",
    "unit_conversion_format": "%1$s %2$s → %3$s %4$s (%5$s)",
    "unlock_advanced_data_and_additional_flashcards": "Desbloquea datos avanzados y tarjetas adicionales.",
    "unlock_advanced_data_and_extra_atomic_content": "Desbloquea datos avanzados y contenido atómico adicional.",
    "usage_statistics": "Estadísticas de uso",
    "vaporization_heat_colon": "Calor de vaporización:",
    "wrong": "Incorrecto",
    "xp_bonus": "+%d%% bonus xp",
    "you_have_full_lives": "¡Tienes todas las vidas!",
    "your_answer": "Tu respuesta: %s",
    "achievement_reached_prefix": "Logro alcanzado: ",
}

# Italian translations
ITALIAN_TRANSLATIONS = {
    "kelvin": "Kelvin",
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit",
    "element_description_title": "Descrizione",
    "favorite_settings_general": "Generale",
    "favorite_settings_nuclear": "Nucleare",
    "sources_settings_title": "Fonti",
    "sources_wwe_text": "Mackenzie L. Davis, (2019). Water and wastewater Engineering: Design Principles and Practise, second edition. ISBN: 978-1-260-13227-4",
    "isotopes_title": "Isotopi",
    "clear_cache_text": "cache_size",
    "submit_bug": "Bug",
    "info_title": "Informazioni",
    "git_title": "Github",
    "activity_ph_neutral": "Neutro",
    "wikipedia_license": "Wikipedia Commons",
    "sothree_license": "Android Sliding Up Panel",
    "calculator_formula": "Formula",
    "short_voltage": "Voltaggio",
    "bug": "Bug",
    "no_results": "Nessun risultato",
    "additional_data_item": "- Dati aggiuntivi:",
    "additional_flashcards_games": "Giochi di flashcard aggiuntivi:",
    "additional_properties_requires_pro": "Proprietà aggiuntive richiedono la versione PRO. Ottieni PRO per sbloccare più dati e tabelle:",
    "additional_tables_item": "- Tabelle aggiuntive:",
    "all_core_features": "Tutte le funzionalità principali",
    "and_more_item": "- E altro",
    "appearance_colon": "Aspetto:",
    "atomic_mass_colon": "Massa atomica:",
    "atomic_number_label": "Numero atomico:",
    "atomic_radius_calculated_colon": "Raggio atomico (calcolato):",
    "atomic_radius_empirical_colon": "Raggio atomico (empirico):",
    "atomic_weight_relative_atomic_mass": "Peso atomico (massa atomica relativa):",
    "balance_equation": "Bilancia equazione:",
    "balance_equation_colon": "Bilancia equazione:",
    "block_colon": "Blocco:",
    "boiling_point_colon": "Punto di ebollizione:",
    "brinell_hardness_colon": "Durezza Brinell:",
    "calculations": "Calcoli",
    "calculations_stat": "Calcoli",
    "card_order": "Ordine carte",
    "color_label": "Colore: ",
    "constants_table_label": "Tabella costanti:",
    "correct": "Corretto",
    "correct_answer": "Risposta corretta: %s",
    "cristal_structure_label": "Struttura cristallina: ",
    "currently_no_favorites": "Attualmente nessun preferito",
    "density_colon": "Densità:",
    "density_label": "Densità: ",
    "electron_shell_colon": "Guscio elettronico:",
    "electronegativity_colon": "Elettronegatività:",
    "elements_included_will_be_shown_here": "Gli elementi inclusi verranno mostrati qui",
    "elements_opened": "Elementi aperti",
    "emission_spectrum_colon": "Spettro di emissione:",
    "enable_zoom_in_tables": "Abilita zoom nelle tabelle",
    "experimental": "Sperimentale",
    "favorites_colon": "Preferiti:",
    "fifty_lives_in_flashcards": "50 vite in flashcard:",
    "finished_game_xp": "Gioco terminato: +%dxp",
    "formula_will_be_displayed_here": "La formula verrà visualizzata qui",
    "fusion_heat_colon": "Calore di fusione:",
    "game_results": "Risultati del gioco",
    "get_pro_button": "Ottieni PRO",
    "get_pro_plus_button": "Ottieni PRO+",
    "go_online_for_emission_lines": "Vai online per le linee di emissione",
    "go_pro_more_features": "Passa a Pro - più funzionalità",
    "go_pro_school_start_sale": "PASSA A PRO - SALDI INIZIO SCUOLA",
    "group_label": "Gruppo: ",
    "hardness_label": "Durezza: ",
    "isotopes_table_description": "Una tabella con isotopi per diversi elementi, nonché dati di emivita, massa, protoni, neutroni e nucleoni.",
    "level_x_y": "Livello X-Y",
    "lives_label": "Vite: %s",
    "lives_lost_detail": "Vite perse: %1$d (%2$d per risposta errata/timeout)",
    "lives_unlimited": "Vite: ∞",
    "magnetism_label": "Magnetismo: ",
    "melting_point_colon": "Punto di fusione:",
    "most_advanced": "Più avanzato",
    "new_label": "NUOVO",
    "next_life_in": "Prossima vita tra %1$d minuti e %2$d secondi.\nGuadagnerai %3$d vita%4$s.",
    "no_image": "Nessuna immagine",
    "non_pro": "NON-PRO",
    "option_placeholder": "Opzione %d",
    "out_of_lives_hours": "Vite esaurite! Altre vite tra %1$d ore, %2$d minuti e %3$d secondi.",
    "out_of_lives_minutes": "Vite esaurite! Altre vite tra %1$d minuti e %2$d secondi.",
    "perfect_all_correct_xp": "Perfetto (Tutto corretto): +%dxp",
    "phase_stp_colon": "Fase (STP):",
    "pro_plus_rewards": "Ricompense PRO+: %s",
    "pro_plus_user": "UTENTE PRO+",
    "pro_plus_version": "Versione PRO+",
    "pro_user": "UTENTE PRO",
    "pro_version": "Versione PRO",
    "progress_xp": "%1$d/%2$d",
    "question_text": "Testo della domanda",
    "questions_correct_xp": "Domande corrette: +%dxp",
    "rate": "Valuta",
    "rate_app": "Valuta app",
    "rate_app_description": "Facci sapere cosa pensi dell'app valutandola su Play Store!",
    "reaction_balancer": "Bilanciatore di reazioni:",
    "score_summary": "Punteggio: %1$d/%2$d",
    "searches": "Ricerche",
    "solubility_table": "Tabella solubilità",
    "specific_heat_capacity_colon": "Capacità termica specifica:",
    "streak_label": "Serie: ",
    "time_up": "Tempo scaduto",
    "tools": "Strumenti",
    "total_xp_stat": "XP totale: %d",
    "type_label": "Tipo: ",
    "unit_conversion_format": "%1$s %2$s → %3$s %4$s (%5$s)",
    "unlock_advanced_data_and_additional_flashcards": "Sblocca dati avanzati e flashcard aggiuntive.",
    "unlock_advanced_data_and_extra_atomic_content": "Sblocca dati avanzati e contenuti atomici aggiuntivi.",
    "usage_statistics": "Statistiche di utilizzo",
    "vaporization_heat_colon": "Calore di vaporizzazione:",
    "wrong": "Sbagliato",
    "xp_bonus": "+%d%% bonus xp",
    "you_have_full_lives": "Hai tutte le vite!",
    "your_answer": "La tua risposta: %s",
    "achievement_reached_prefix": "Obiettivo raggiunto: ",
}

# Portuguese translations  
PORTUGUESE_TRANSLATIONS = {
    "kelvin": "Kelvin",
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit",
    "element_description_title": "Descrição",
    "favorite_settings_general": "Geral",
    "favorite_settings_nuclear": "Nuclear",
    "sources_settings_title": "Fontes",
    "sources_wwe_text": "Mackenzie L. Davis, (2019). Water and wastewater Engineering: Design Principles and Practise, second edition. ISBN: 978-1-260-13227-4",
    "isotopes_title": "Isótopos",
    "clear_cache_text": "cache_size",
    "submit_bug": "Bug",
    "info_title": "Informação",
    "git_title": "Github",
    "activity_ph_neutral": "Neutro",
    "wikipedia_license": "Wikipedia Commons",
    "sothree_license": "Android Sliding Up Panel",
    "calculator_formula": "Fórmula",
    "short_voltage": "Voltagem",
    "bug": "Bug",
    "no_results": "Sem resultados",
    "additional_data_item": "- Dados adicionais:",
    "additional_flashcards_games": "Jogos de cartões adicionais:",
    "additional_properties_requires_pro": "Propriedades adicionais requerem versão PRO. Obtenha PRO para desbloquear mais dados e tabelas:",
    "additional_tables_item": "- Tabelas adicionais:",
    "all_core_features": "Todos os recursos principais",
    "and_more_item": "- E mais",
    "appearance_colon": "Aparência:",
    "atomic_mass_colon": "Massa atômica:",
    "atomic_number_label": "Número atômico:",
    "atomic_radius_calculated_colon": "Raio atômico (calculado):",
    "atomic_radius_empirical_colon": "Raio atômico (empírico):",
    "atomic_weight_relative_atomic_mass": "Peso atômico (massa atômica relativa):",
    "balance_equation": "Balancear equação:",
    "balance_equation_colon": "Balancear equação:",
    "block_colon": "Bloco:",
    "boiling_point_colon": "Ponto de ebulição:",
    "brinell_hardness_colon": "Dureza Brinell:",
    "calculations": "Cálculos",
    "calculations_stat": "Cálculos",
    "card_order": "Ordem dos cartões",
    "color_label": "Cor: ",
    "constants_table_label": "Tabela de constantes:",
    "correct": "Correto",
    "correct_answer": "Resposta correta: %s",
    "cristal_structure_label": "Estrutura cristalina: ",
    "currently_no_favorites": "Atualmente sem favoritos",
    "density_colon": "Densidade:",
    "density_label": "Densidade: ",
    "electron_shell_colon": "Camada eletrônica:",
    "electronegativity_colon": "Eletronegatividade:",
    "elements_included_will_be_shown_here": "Os elementos incluídos serão mostrados aqui",
    "elements_opened": "Elementos abertos",
    "emission_spectrum_colon": "Espectro de emissão:",
    "enable_zoom_in_tables": "Ativar zoom nas tabelas",
    "experimental": "Experimental",
    "favorites_colon": "Favoritos:",
    "fifty_lives_in_flashcards": "50 vidas em cartões:",
    "finished_game_xp": "Jogo terminado: +%dxp",
    "formula_will_be_displayed_here": "A fórmula será exibida aqui",
    "fusion_heat_colon": "Calor de fusão:",
    "game_results": "Resultados do jogo",
    "get_pro_button": "Obter PRO",
    "get_pro_plus_button": "Obter PRO+",
    "go_online_for_emission_lines": "Ir online para linhas de emissão",
    "go_pro_more_features": "Ir Pro - mais recursos",
    "go_pro_school_start_sale": "IR PRO - VENDA DE VOLTA ÀS AULAS",
    "group_label": "Grupo: ",
    "hardness_label": "Dureza: ",
    "isotopes_table_description": "Uma tabela com isótopos para diferentes elementos, bem como dados de meia-vida, massa, prótons, nêutrons e núcleons.",
    "level_x_y": "Nível X-Y",
    "lives_label": "Vidas: %s",
    "lives_lost_detail": "Vidas perdidas: %1$d (%2$d por resposta errada/tempo esgotado)",
    "lives_unlimited": "Vidas: ∞",
    "magnetism_label": "Magnetismo: ",
    "melting_point_colon": "Ponto de fusão:",
    "most_advanced": "Mais avançado",
    "new_label": "NOVO",
    "next_life_in": "Próxima vida em %1$d minutos e %2$d segundos.\nVocê ganhará %3$d vida%4$s.",
    "no_image": "Sem imagem",
    "non_pro": "NÃO-PRO",
    "option_placeholder": "Opção %d",
    "out_of_lives_hours": "Sem vidas! Mais vidas em %1$d horas, %2$d minutos e %3$d segundos.",
    "out_of_lives_minutes": "Sem vidas! Mais vidas em %1$d minutos e %2$d segundos.",
    "perfect_all_correct_xp": "Perfeito (Tudo correto): +%dxp",
    "phase_stp_colon": "Fase (STP):",
    "pro_plus_rewards": "Recompensas PRO+: %s",
    "pro_plus_user": "USUÁRIO PRO+",
    "pro_plus_version": "Versão PRO+",
    "pro_user": "USUÁRIO PRO",
    "pro_version": "Versão PRO",
    "progress_xp": "%1$d/%2$d",
    "question_text": "Texto da pergunta",
    "questions_correct_xp": "Perguntas corretas: +%dxp",
    "rate": "Avaliar",
    "rate_app": "Avaliar aplicativo",
    "rate_app_description": "Deixe-nos saber o que você pensa do aplicativo avaliando-o na Play Store!",
    "reaction_balancer": "Balanceador de reações:",
    "score_summary": "Pontuação: %1$d/%2$d",
    "searches": "Pesquisas",
    "solubility_table": "Tabela de solubilidade",
    "specific_heat_capacity_colon": "Capacidade calorífica específica:",
    "streak_label": "Sequência: ",
    "time_up": "Tempo esgotado",
    "tools": "Ferramentas",
    "total_xp_stat": "XP total: %d",
    "type_label": "Tipo: ",
    "unit_conversion_format": "%1$s %2$s → %3$s %4$s (%5$s)",
    "unlock_advanced_data_and_additional_flashcards": "Desbloqueie dados avançados e cartões adicionais.",
    "unlock_advanced_data_and_extra_atomic_content": "Desbloqueie dados avançados e conteúdo atômico adicional.",
    "usage_statistics": "Estatísticas de uso",
    "vaporization_heat_colon": "Calor de vaporização:",
    "wrong": "Errado",
    "xp_bonus": "+%d%% bonus xp",
    "you_have_full_lives": "Você tem todas as vidas!",
    "your_answer": "Sua resposta: %s",
    "achievement_reached_prefix": "Conquista alcançada: ",
}

# Map languages to their translation dictionaries
TRANSLATION_DICTS = {
    'values-de': GERMAN_TRANSLATIONS,
    'values-fr': FRENCH_TRANSLATIONS,
    'values-es-rAR': SPANISH_TRANSLATIONS,
    'values-es-rES': SPANISH_TRANSLATIONS,
    'values-es-rMX': SPANISH_TRANSLATIONS,
    'values-pt-rBR': PORTUGUESE_TRANSLATIONS,
    'values-it-rIT': ITALIAN_TRANSLATIONS,
}

# Strings that should not be translated
SKIP_STRINGS = [
    'bluesky', 'instagram', 'facebook', 'homepage', 'about_author_name',
    'mackenzie_l_davis', 'water_and_wastewater_engineering',
    'sothree_android_sliding_up_panel', 'wikipedia_commons',
    'credits_giancarlo', 'credits_electro_boy', 'app_name',
    'web_client_id', 'pro_price_discount', 'blog'
]

def apply_translations(repo_path):
    """Apply manual translations to string resource files."""
    print("\n" + "=" * 80)
    print("APPLYING MANUAL TRANSLATIONS")
    print("=" * 80)
    
    res_path = os.path.join(repo_path, "app/src/main/res")
    
    # Read English strings as reference
    en_strings_path = os.path.join(res_path, "values/strings.xml")
    tree = ET.parse(en_strings_path)
    root = tree.getroot()
    en_strings = {}
    for string_elem in root.findall('string'):
        name = string_elem.get('name')
        translatable = string_elem.get('translatable')
        if translatable != 'false':
            en_strings[name] = string_elem.text if string_elem.text else ''
    
    total_translated = 0
    
    # Process each language that has translations
    for values_dir, translations in TRANSLATION_DICTS.items():
        strings_file = os.path.join(res_path, values_dir, "strings.xml")
        if not os.path.exists(strings_file):
            print(f"\n{values_dir}: File not found, skipping")
            continue
        
        print(f"\n{values_dir}:")
        
        # Parse existing file
        tree = ET.parse(strings_file)
        root = tree.getroot()
        
        trans_count = 0
        
        # Apply translations
        for string_elem in root.findall('string'):
            name = string_elem.get('name')
            current_text = string_elem.text if string_elem.text else ''
            
            # Skip if not in English strings or should not be translated
            if name not in en_strings or name in SKIP_STRINGS:
                continue
            
            # Check if needs translation and we have a translation for it
            if current_text == en_strings[name] and name in translations:
                string_elem.text = translations[name]
                trans_count += 1
                print(f"  ✓ {name}")
        
        # Save updated file
        tree.write(strings_file, encoding='utf-8', xml_declaration=True)
        print(f"\n  Total translated: {trans_count} strings")
        total_translated += trans_count
    
    print("\n" + "=" * 80)
    print(f"COMPLETE! Translated {total_translated} total strings")
    print("=" * 80)

def main():
    """Main function."""
    if len(sys.argv) > 1:
        repo_path = sys.argv[1]
    else:
        repo_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    print("Starting manual translation application...")
    print(f"Repository: {repo_path}")
    
    apply_translations(repo_path)

if __name__ == "__main__":
    main()
